// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hello.proto

package com.leuncle.demo.model;

public interface HelloRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.leuncle.demo.grpc.HelloRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int32 id = 2;</code>
   */
  int getId();
}
